# Generated by Django 4.1 on 2022-08-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(blank=True, choices=[('ofitsiant', 'ofitsiant'), ('boshqaruvchi', 'boshqaruvchi'), ('kassir', 'kassir'), ('deliverer', 'deliverer')], max_length=50, null=True),
        ),
    ]
