# Generated by Django 4.1 on 2022-08-18 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_poll_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='product_category',
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
