# Generated by Django 4.1 on 2022-08-19 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_offer_product_category_offer_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='user_category',
        ),
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_category', models.CharField(blank=True, max_length=50, null=True)),
                ('question', models.CharField(blank=True, max_length=50, null=True)),
                ('variant', models.CharField(blank=True, max_length=50, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
                ('tg_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tguser')),
            ],
        ),
    ]
