# Generated by Django 4.1 on 2022-08-21 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_variant_remove_poll_variant1_remove_poll_variant2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollresult',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.variant'),
        ),
    ]
