# Generated by Django 4.1 on 2022-08-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_pollresult_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.ImageField(blank=True, null=True, upload_to='bot_photos/')),
                ('start', models.ImageField(blank=True, null=True, upload_to='bot_photos/')),
                ('product', models.ImageField(blank=True, null=True, upload_to='bot_photos/')),
            ],
        ),
    ]
